// components/data.dart
class DataApp {
  Map data = {
    "title" : 
    {"ar":"سيف المرقاب للأمن","en":"Saif Al Mirgab For Security"},
    "private" : { "ar" : "اختيارك لشركة الأمن الخاصة" , "en" : "Your Private Security Comapany Choice "},
    "privatetext" : { "ar" : "في شركة سيف المرقاب للأمن، هدفنا الوحيد هو أن نصبح اسمًا مألوفًا في صناعة الأمن الخاصة، من خلال إثبات قدرتنا عمليًا على تقديم خدمات الحماية المهنية للصناعات والمنازل التجارية والأفراد ضمن منطقة عملنا بأسعار تنافسية للغاية." , "en" : "At Saif Al Mirgab Security, our sole objective is to become a household name in the private\nsecurity industry, by practically demonstrating the ability to provide professional\nprotective services to industries, commercial houses and private individuals\nwithin our area of operation at very competitive rates."},
    "distingushed" : {"ar" : "تاريخ عملنا المتميز" , "en" : "Our distinguished work history"},
    "distingushedtext" : { "ar" : "تاريخ عملنا في سيف المرقاب. في سيف المرقاب، نتمتع بسجل حافل في توفير حراس أمن محترفين ومدربين تدريبًا عاليًا. بفضل خبرتنا الواسعة في المواقع الحكومية والتجارية والمواقع شديدة الحراسة، يشتهر فريقنا بالموثوقية والانضباط والالتزام بالسلامة. نقدم حماية موثوقة ونزاهة.", "en" : "Our Work History in Saif Al Mirgab  At Saif Al Mirgab, we have built a strong track record in providing professional, well-trained security guards. With proven experience across government, commercial, and high-security sites, our team is known for reliability, discipline, and commitment to safety. We deliver trusted protection with integrity." },
    "services" : { "ar" : "خدماتنا", "en" : "OUR SERVICES"},
    "Reception" : { "ar" : "أمن الاستقبال/الفعاليات", "en" : "Reception/Event Security"},
    "Protocol" : { "ar" : "خدمات البروتوكول والمرافقة", "en" : "Protocol & Escort Services"},
    "Corporate" : { "ar" : "المكتب الرئيسي", "en" : "Corporate Office"},
    "Security" : { "ar" : "حراس الأمن", "en" : "Security Guards"},
    "Body" : { "ar" : "خدمات الحراسة الشخصية", "en" : "Body Guard Services"},
    "Close" : { "ar" : "خدمات الحماية الوثيقة", "en" : "Close Protection Services"},
    "ABOUT" : { "ar" : "معلومات عنا", "en" : "ABOUT US"},
    "leading" : { "ar" : "سيف المرقاب شركة رائدة في تقديم خدمات الحراسة الأمنية الاحترافية، ملتزمة بحماية الأفراد والممتلكات والأصول بنزاهة وتميز. بفضل خبرتنا الواسعة وسمعة طيبة في مجال الموثوقية، نقدم حلولاً أمنية مصممة خصيصاً للقطاعات الحكومية والتجارية والخاصة. حراسنا مدربون تدريباً عالياً، ومنضبطون، ومدعومون بأحدث الأنظمة لضمان أقصى درجات الكفاءة والسلامة. في سيف المرقاب، أمنكم هو رسالتنا.", "en" : "Saif Al Mirgab is a leading provider of professional security guard services, committed to protecting people, property, and assets with integrity and excellence. With a strong foundation of experience and a reputation for reliability, we deliver tailored security solutions across government, commercial, and private sectors. Our guards are highly trained, disciplined, and supported by modern systems to ensure maximum efficiency and safety. At Saif Al Mirgab, your security is our mission."},
    "Recruitment" : { "ar" : "قسم التوظيف", "en" : "Recruitment Department"},
    "our_Recruitment" : { "ar" : "في سيف المرقاب، يلعب قسم التوظيف دورًا حيويًا في الحفاظ على المعايير العالية التي تُميز خدماتنا الأمنية. نؤمن بأن الأمن الاستثنائي يبدأ بأفراد استثنائيين. ولذلك، صُممت عملية التوظيف لدينا لتحديد الأفراد الذين يُظهرون الاحترافية والانضباط والنزاهة والشعور القوي بالمسؤولية.\nيتبع فريقنا عملية اختيار دقيقة تتضمن تحريات عن الخلفية، وتقييمات بدنية ونفسية، ومقابلات شاملة لضمان استيفاء كل مرشح لمعاييرنا التشغيلية والأخلاقية. نولي الأولوية للخبرة والإمكانات، ونرحب بالمحترفين المهرة، وكذلك الوافدين الجدد المتحمسين والمستعدين لتلقي تدريب مكثف.\nإلى جانب التوظيف، يعمل قسم التوظيف بشكل وثيق مع فرق التدريب والعمليات لدينا لضمان تزويد كل حارس جديد بالمعرفة والأدوات والعقلية اللازمة للأداء الفعال في الميدان.", "en" : "At Saif Al Mirgab, our Recruitment Department plays a vital role in maintaining the high standards that define our security services. We believe that exceptional security starts with exceptional people. That’s why our recruitment process is designed to identify individuals who demonstrate professionalism, discipline, integrity, and a strong sense of responsibility.\nOur team follows a rigorous selection process that includes background checks, physical and psychological assessments, and thorough interviews to ensure each candidate meets our operational and ethical standards. We prioritize both experience and potential, welcoming skilled professionals as well as motivated newcomers who are ready to undergo intensive training.\nBeyond hiring, the Recruitment Department works closely with our Training and Operations teams to ensure every new guard is equipped with the knowledge, tools, and mindset to perform effectively in the field."},
    "certificates" : { "ar" : "شهادات التميز لدينا دليل على التزامنا", "en" : "Our certificates of excellence evidence\nof our commitment"},
    "call" : { "ar" : "تواصل معنا", "en" : "CALL US"},
    "call_us_text" : { "ar" : "إذا كنت تبحث عن شريك أمني موثوق يضع سلامتك في المقام الأول، فنحن هنا لتلبية توقعاتك. في سيف المرقاب، لا نقدم خدمات فحسب، بل نوفر لك راحة البال. فريقنا مستعد لتلبية احتياجاتك وتقديم الحلول المناسبة باحترافية وعناية. لا تتردد، تواصل معنا، ولنبدأ رحلتنا معًا نحو بيئة أكثر أمانًا.", "en" : 'If you are looking for a reliable security partner who puts your safety first, we are here to\n meet your expectations. At Saif Al Mirqab, we dont just provide services—we offer peace of\n mind. Our team is ready to listen to your needs and provide appropriate solutions with\n professionalism and care. Dont hesitate, contact us and letis begin our journey together\n toward a safer environment.'},
    "Pages" : { "ar" : "الصفحات", "en" : "Our Pages"},
    "home" : { "ar" : "الرئيسية - من نحن - تواصل معنا - الخدمات\nقسم التوظيف", "en" : 'HOME - ABOUT US - CALL US - SERVICES\nRecruitment Department'},
    "text" : { "ar" : "سيف المرقاب للأمن", "en" : "Saif Al Mirgab For Security"},
    "textdown" : { "ar" : "سيف المرقاب... الحماية التي تبدأ بالثقة وتستمر بالالتزام.", "en" : "Saif Al-Mirqab... protection that begins with trust and continues with commitment."},
    "homefinish" : { "ar" : "جميع الحقوق محفوظة لشركة سيف المرقاب للحراسات الأمنية", "en" : "All rights reserved to Saif Al Mirgab Security Company"},
  };
}
